### ISSUE TITLE
JSON not sorting keys

### ISSUE THREAD

**Issue by laussy** [indigane/cardsort#5]
This is great material and a convenient, self-contained used of the muuri toolkit.

However it seems to have a big shortcoming for a card sorter: it does not sort them! Since JSON does not guarantee that the order in the array remains the same, the cards that are ordered in one category are exported in a different order, which makes the whole point useless to me as I am interested in the order in each category (which card comes first, which 2nd, etc.) Is there an easy way to fix this?

**Comment by indigane** [comment]
You are correct. I'll look into this. I agree that it would be good for the cards to keep their order.

Just for reference when I have time to come back to this:

[Categories ordered 1, 2, 3. Cards ordered A, B, C within category.](https://indigane.github.io/cardsort/card-sort.html#eJxNkcFOwzAMhl8Flesug9suaBTYgU2r2CSEEAc389qoSRy5CdOEeHcSZ51QpPhP8vm3rfxUK6bob-bV4rNaem-wmlWP4NJKooa2hQ6rr9kFuysYa0UhgwhOMBfApPd_5L2QHLTqaRBTxCAsg23JQEZvBRp9uuvimF6X36TgQIIbc9Og98j5ZEANLTKf5RDxqpmUIqOLM1MpEY0-GjpJao0GBa37S05NilwUklj6Z3CTYR1VtK1kPkHIjT93nTdpwiRfdJf2FbDRKgui8drJisHjkaMO0yHFV33S090acZBgyUkMIaoMrbXNYQOuy5Nv4tgzkU1y67Sw29Rgl5kGPJxBBI9O-6wQVF8il5B37RAuv9mYmL0astglnzJUQwFCrtZE6wedi7zBQY-9iNFPU-28dsV_FxhO0_WebEnfRy5tvCdftmik3w-w-XsfqsX89w8oWMKE)

[Categories ordered 2, 3, 1. Cards ordered C, B, A within category.](https://indigane.github.io/cardsort/card-sort.html#eJxFUcFOwzAM_RVUrrsMbrugUWAHNq1ikxBCHNzMa6MmceQmTBPi30mcdahS3nPy_PKc_lQrpuhv7qrFZ7X0rBWFalbV4AKYdICpeERw1dfsorwXJQetehpQtAy2JQMixfAvnRdTb4qsbaETP3Dpy7JbEYw-OXRxTEfLb1JwIHEy5qZB75FzZUANLTKfpYh45UxKkdElB1_CR6OPhk7SWqNBkdb9pacmRS6KkthlYHCTYR1VtK10PkHIcZ-7zpv0Hom-6C6tK2CjVSZE4zXJisHjkaMOU5HwVZ_0tLdGHAQsOcEQosqitbYZNuC6PPkmjj0T2US3Tot2mwLK0zXg4QxCeHTaZ4ag-oJcIK_aIVwevjExezVksUs-ZaiGAoR8WxOtH3S-5A0OeuyFjH6aaue1K_67wHCatvdkS_s-conxnnzZopG8H2Dz732oFvPfP2YQwoQ=)

The second example does not retain the C, B, A order, but retains the order of categories.

**Comment by indigane** [comment]
This was happening because the order of the cards was being read from DOM, without calling [`grid.synchronize()`](https://github.com/haltu/muuri/blob/219e008/README.md#grid-method-synchronize) to make the DOM order match the Muuri grid order.

Either the order should have been read from Muuri, or the DOM order should have been updated.

I went with calling `grid.synchronize()`, although if I were to rewrite the app, I think it would be more reliable to read the order from Muuri.

Let me know if you find that the issue persists. There may be some timing issues I have not figured out yet.
